/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./../components/ui/AppAvatar.vue')['default']
    AppButton: typeof import('./../components/ui/AppButton.vue')['default']
    AppCard: typeof import('./../components/ui/AppCard.vue')['default']
    AppConfirm: typeof import('./../components/ui/AppConfirm.vue')['default']
    AppDialog: typeof import('./../components/ui/AppDialog.vue')['default']
    AppDropdown: typeof import('./../components/ui/AppDropdown.vue')['default']
    AppEmpty: typeof import('./../components/ui/AppEmpty.vue')['default']
    AppFormItem: typeof import('./../components/ui/AppFormItem.vue')['default']
    AppInput: typeof import('./../components/ui/AppInput.vue')['default']
    AppLoading: typeof import('./../components/ui/AppLoading.vue')['default']
    AppMultiSelect: typeof import('./../components/ui/AppMultiSelect.vue')['default']
    AppPagination: typeof import('./../components/ui/AppPagination.vue')['default']
    AppRadioGroup: typeof import('./../components/ui/AppRadioGroup.vue')['default']
    AppSearch: typeof import('./../components/ui/AppSearch.vue')['default']
    AppSelect: typeof import('./../components/ui/AppSelect.vue')['default']
    AppSwitch: typeof import('./../components/ui/AppSwitch.vue')['default']
    AppTable: typeof import('./../components/ui/AppTable.vue')['default']
    AppTabs: typeof import('./../components/ui/AppTabs.vue')['default']
    AppTag: typeof import('./../components/ui/AppTag.vue')['default']
    AppTextarea: typeof import('./../components/ui/AppTextarea.vue')['default']
    AppToaster: typeof import('./../components/ui/AppToaster.vue')['default']
    AppTooltip: typeof import('./../components/ui/AppTooltip.vue')['default']
    AppUpload: typeof import('./../components/ui/AppUpload.vue')['default']
    MarkdownView: typeof import('./../components/MarkdownView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
